dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
  - sudo apt-get install -y lcov
  - git submodule update --init --recursive

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -Hsrc -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build
  - make
  - ./YAIP++

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
